package de.scout24.financing.domain.enums;

public enum ExfoPermission {
    SEARCH_SITE,
    VIEW_QUESTIONS,
    CREATE_QUESTIONS,
    PUBLISH_QUESTIONS,
    EDIT_QUESTIONS,
    ADD_CATEGORIES,
    ANSWER_QUESTIONS,
    COMMENT_OWN_ANSWERS,
    COMMENT_ALL_ANSWERS,
    RATE_ANSWERS,
    EDIT_ANSWERS,
    EDIT_OWN_USER_PROFILE,
    EDIT_ALL_USER_PROFILES,
    RESET_OWN_PASSWORD,
    RESET_ALL_PASSWORDS,
    ABANDON_USER,
    APPROVE_EXPERTS,
    CREATE_PLATFORM,
    EDIT_USER_GRANTS
}
