package de.scout24.financing.domain.enums;

public enum NotificationEventType{
    QUESTION_CREATED,
    QUESTION_UPDATED,
    QUESTION_CLOSED,
    QUESTION_REJECTED,
    QUESTION_SPAMMED,

    ANSWER_CREATED,
    ANSWER_UPDATED,
    ANSWER_COMMENTED_BY_EXPERT,
    ANSWER_COMMENTED_BY_USER,

    SUPPORT_CONTACT,//USER GETS A MAIL FROM SUPPORT FOR WHATEVER REASON
    EXPERT_CONTACT;//EXPERT GETS ALL INFO OF USER WHO WANTS TO CONTACT HIM;

}
